/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Role = {
  _id: string;
  _type: "role";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type RoleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "role";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Testimony = {
  _id: string;
  _type: "testimony";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  testimony?: string;
  name?: string;
  slug?: Slug;
  roles?: Array<
    {
      _key: string;
    } & RoleReference
  >;
  company?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  showOnHomepage?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  link?: string;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  showOnHomepage?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Role
  | Slug
  | Category
  | RoleReference
  | SanityImageAssetReference
  | Testimony
  | SanityImageCrop
  | SanityImageHotspot
  | CategoryReference
  | CaseStudy
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: getAllCaseStudiesQuery
// Query: *[_type == "caseStudy"] | order(_createdAt desc) {    _id,    name,    "slug": slug.current,    description,    "imageUrl": image.asset->url,    image,    link,    "categories": categories[]->title  }
export type GetAllCaseStudiesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  imageUrl: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  link: string | null;
  categories: Array<string | null> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: getHomepageCaseStudiesQuery
// Query: *[_type == "caseStudy" && showOnHomepage == true] | order(_createdAt desc) {    _id,    name,    "slug": slug.current,    description,    "imageUrl": image.asset->url,    image,    link,    "categories": categories[]->title  }
export type GetHomepageCaseStudiesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  imageUrl: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  link: string | null;
  categories: Array<string | null> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: getAllTestimoniesQuery
// Query: *[_type == "testimony"] | order(_createdAt asc) {    _id,    testimony,    name,    "slug": slug.current,    "roles": roles[]->title,    company,    "imageUrl": image.asset->url,    image  }
export type GetAllTestimoniesQueryResult = Array<{
  _id: string;
  testimony: string | null;
  name: string | null;
  slug: string | null;
  roles: Array<string | null> | null;
  company: string | null;
  imageUrl: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: getHomepageTestimoniesQuery
// Query: *[_type == "testimony" && showOnHomepage == true] | order(_createdAt asc)[0...3] {    _id,    testimony,    name,    "slug": slug.current,    "roles": roles[]->title,    company,    "imageUrl": image.asset->url,    image  }
export type GetHomepageTestimoniesQueryResult = Array<{
  _id: string;
  testimony: string | null;
  name: string | null;
  slug: string | null;
  roles: Array<string | null> | null;
  company: string | null;
  imageUrl: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "caseStudy"] | order(_createdAt desc) {\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    "imageUrl": image.asset->url,\n    image,\n    link,\n    "categories": categories[]->title\n  }\n': GetAllCaseStudiesQueryResult;
    '\n  *[_type == "caseStudy" && showOnHomepage == true] | order(_createdAt desc) {\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    "imageUrl": image.asset->url,\n    image,\n    link,\n    "categories": categories[]->title\n  }\n': GetHomepageCaseStudiesQueryResult;
    '\n  *[_type == "testimony"] | order(_createdAt asc) {\n    _id,\n    testimony,\n    name,\n    "slug": slug.current,\n    "roles": roles[]->title,\n    company,\n    "imageUrl": image.asset->url,\n    image\n  }\n': GetAllTestimoniesQueryResult;
    '\n  *[_type == "testimony" && showOnHomepage == true] | order(_createdAt asc)[0...3] {\n    _id,\n    testimony,\n    name,\n    "slug": slug.current,\n    "roles": roles[]->title,\n    company,\n    "imageUrl": image.asset->url,\n    image\n  }\n': GetHomepageTestimoniesQueryResult;
  }
}
