export interface PricingRow {
  label: string;
  note?: string;
  starter: string;
  growth: string;
  enterprise: string;
}

export interface PricingSection {
  title: string;
  rows: PricingRow[];
}

export const TIERS = ["Starter", "Growth", "Enterprise"] as const;
export type Tier = (typeof TIERS)[number];

export const TIER_SUBTITLES: Record<Tier, string> = {
  Starter: "For small teams & early-stage businesses",
  Growth: "For scaling businesses",
  Enterprise: "For complex, high-volume needs",
};

export const SECTIONS: PricingSection[] = [
  {
    title: "Core Services",
    rows: [
      {
        label: "Web Development",
        note: "Landing pages & websites",
        starter: "£299 – £1,200",
        growth: "£1,200 – £3,800",
        enterprise: "Custom",
      },
      {
        label: "SaaS / Mobile / Desktop App",
        note: "Full product builds",
        starter: "£1,200 – £2,300",
        growth: "£2,300 – £7,500",
        enterprise: "£7,500 – £18,600+",
      },
      {
        label: "AI Automation",
        note: "Chatbots, workflows & AI agents",
        starter: "£800 – £1,700",
        growth: "£1,700 – £5,200",
        enterprise: "£5,200 – £14,900+",
      },
    ],
  },
  {
    title: "Growth & Marketing",
    rows: [
      {
        label: "Lead Gen Ads",
        starter: "£500 – £1,000",
        growth: "£1,000 – £3,000",
        enterprise: "£3,000 – £10,000",
      },
      {
        label: "DTC Ads",
        note: "Video & creative campaigns",
        starter: "£800 – £1,500",
        growth: "£1,500 – £5,000",
        enterprise: "£5,500 – £20,000+",
      },
      {
        label: "SEO",
        starter: "£500 – £1,000",
        growth: "£1,000 – £5,000",
        enterprise: "Custom",
      },
      {
        label: "Email Marketing",
        starter: "£500 – £1,000",
        growth: "£1,000 – £3,000",
        enterprise: "Custom",
      },
      {
        label: "Organic Social",
        starter: "£500 – £1,000",
        growth: "Custom",
        enterprise: "Custom",
      },
    ],
  },
  {
    title: "Creative",
    rows: [
      {
        label: "Copywriting",
        note: "Per written piece",
        starter: "£250 – £500",
        growth: "Custom",
        enterprise: "Custom",
      },
      {
        label: "Creative Production",
        note: "Photography, graphics & assets",
        starter: "£500 – £1,500",
        growth: "Custom",
        enterprise: "Custom",
      },
    ],
  },
];

export interface PerformanceRow {
  model: string;
  offer: string;
  example: string;
}

export const PERFORMANCE_MODELS: PerformanceRow[] = [
  {
    model: "Pay Per Lead",
    offer: "You pay only for qualified leads generated by our campaigns.",
    example: "At £50/lead, 100 qualified leads = £5,000. Lead qualification criteria agreed upfront.",
  },
  {
    model: "Pay Per Sale",
    offer: "Commission-based — we earn a percentage of each sale we drive.",
    example: "At 10% commission on £50,000 in sales = £5,000. Typical rate: 5–20% depending on product.",
  },
];
